//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Test.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_TestTYPE                    130
#define IDD_JIXIESHEJI_DIALOG           315
#define IDR_ICONS                       319
#define IDR_DIALOG_LARGE                322
#define IDB_BITMAP1                     323
#define IDB_WORKSPACE                   323
#define IDB_TOOLBAR256                  324
#define IDB_BACK_BLUE                   326
#define IDB_BACK_DARK                   328
#define IDD_TULUN_DIALOG                333
#define IDB_BITMAP3                     336
#define IDB_PNG1                        342
#define IDR_IMAGES                      342
#define IDD_CAFFE_DIALOG                343
#define IDB_CAFFE_TYPE_BITMAP           344
#define IDB_BITMAP4                     345
#define IDB_PEILIAO_BITMAP              345
#define IDD_BOSS_DIALOG                 346
#define IDD_LOGIN_DIALOG                347
#define IDD_SELL_DIALOG                 348
#define IDC_CHILUN_BUTTON               1018
#define IDC_WOGAN_BUTTON                1019
#define IDC_WOGANSHOUMING_EDIT2         1033
#define ID_IMAGES_GALLERY               1043
#define ID_VIEW_WORKSPACE               1044
#define IDC_LEIXING_COMBO               1062
#define IDC_FANGXIANG_COMBO             1063
#define IDC_TUI_COMBO                   1064
#define IDC_HUI_COMBO                   1065
#define IDC_TUI_EDIT                    1066
#define IDC_HUI_EDIT                    1067
#define IDC_JINXIU_EDIT                 1068
#define IDC_YUANXIU_EDIT                1069
#define IDC_BAIFU_EDIT                  1070
#define IDC_JIYUAN_EDIT                 1071
#define IDC_PIANJU_EDIT                 1072
#define IDC_ZHONGXIN_EDIT               1073
#define IDC_TUIYALI_EDIT                1074
#define IDC_YALIJIAO_EDIT               1075
#define IDC_GUNZI_EDIT                  1076
#define IDC_GAN_EDIT                    1077
#define IDC_XINCHENG_EDIT2              1078
#define IDC_XINCHENG_EDIT               1078
#define IDC_TUI_SPIN                    1079
#define IDC_YUANXIU__SPIN               1080
#define IDC_HUI_SPIN                    1081
#define IDC_BAIFU_SPIN                  1082
#define IDC_JIYUAN_SPIN                 1083
#define IDC_PIANJU_SPIN                 1084
#define IDC_ZHONGXIN_SPIN               1085
#define IDC_GAN_SPIN                    1086
#define IDC_GUNZI_SPIN                  1087
#define IDC_TCHART1                     1088
#define IDC_XINGCHENG_SPIN              1089
#define IDC_LUNKUO_CHECK                1090
#define IDC_WAIKUO_CHECK                1091
#define IDC_NEIKUO_CHECK                1092
#define IDC_JIYUAN_CHECK                1093
#define IDC_ZHONGXIN_CHECK              1094
#define IDC_CONG_CHECK                  1095
#define IDC_XUANZHUAN_EDIT              1096
#define IDC_ZUOBIAO_EDIT                1097
#define IDC_NEIBIAO_EDIT                1098
#define IDC_XUANZHUANJIAO_STATIC        1099
#define IDC_LUOBIAO_STATIC              1100
#define IDC_NEIBIAO_STATIC              1101
#define IDC_WAIBIAO_STATIC              1102
#define IDC_WAIBIAO_EDIT                1103
#define IDC_XUANZHUAN_BUTTON            1104
#define IDC_ZANTING_BUTTON              1105
#define IDC_FANGDA_BUTTON               1106
#define IDC_SUOXIAO_BUTTON              1107
#define IDC_FUWEI_BUTTON                1108
#define IDC_SHUAXIN_BUTTON              1109
#define IDC_SHIKUO_CHECK                1110
#define IDC_XUANZHUAJIAO_SPIN           1111
#define IDC_BAIFU_STATIC                1112
#define IDC_GAN_STATIC                  1113
#define IDC_ZHONGXIN_STATIC             1114
#define IDC_GUNZI_STATIC                1115
#define IDC_PIANJU_STATIC               1116
#define IDC_COMBO2                      1117
#define IDC_PIANJU_COMBO                1117
#define IDC_XINGCHENG_STATIC            1118
#define IDC_CAFFE_TYPE_STATIC           1120
#define IDC_PEILIAO_STATIC              1121
#define IDC_IMAGE_CAFFETYPE             1122
#define IDC_IMAGE_PEILIAO               1122
#define IDC_USERNAME_EDIT               1122
#define IDC_PASSWORD_EDIT               1123
#define IDC_MAN_BUTTON                  1123
#define IDC_CAFFE_BUTTON                1124
#define IDC_BAR_TCHART                  1125
#define IDC_PIE_TCHART                  1126
#define IDC_SELL_BUTTON2                1127
#define IDC_SELL_BUTTON                 1127
#define IDC_YEAR_COMBO                  1127
#define IDC_COMBO3                      1128
#define IDC_MONTH_COMBO                 1128
#define IDC_MONTH_COMBO2                1129
#define IDC_BARPIE_COMBO                1129

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        350
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1128
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
